# Databricks Apps configuration
# https://docs.databricks.com/dev-tools/databricks-apps/app-runtime

name: snap
description: Executive Fiscal ROI — SNAP PER & Income Latency Dashboard

# Run Streamlit on port 8080 (required by Databricks Apps)
command: ['streamlit', 'run', 'app.py']

# Real data: add a SQL warehouse as app resource in the workspace, then deploy.
env:
  USE_MOCK_BACKEND: "false"
