# Databricks Apps configuration
# https://docs.databricks.com/dev-tools/databricks-apps/app-runtime

name: snap
description: Executive Fiscal ROI — SNAP PER & Income Latency Dashboard

# Run Streamlit on port 8080 (required by Databricks Apps)
command: ['streamlit', 'run', 'app.py']

# Real data: add a SQL warehouse as app resource in the workspace, then deploy.
env:
  - name: 'DATABRICKS_HOST'
    value: 'adb-3438839487639471.11.azuredatabricks.net/'
  - name: 'DATABRICKS_WAREHOUSE_ID'
    value: 'a94a22f8652d85c1'
  - name: 'USE_MOCK_BACKEND'
    value: 'false'
 